import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { createPilotTicketCore } from '../src/p1-005-pilot-ticket-core.mjs';
import { appendTicketEvent } from '../src/p1-006-ticket-state-actions.mjs';
import { createPilotAccessService } from '../src/p1-009-pilot-access-workbench.mjs';
import { createP2016TicketNotificationProjector } from '../src/p2-016-ticket-notification-projector.mjs';
import { createP2016TicketQuery } from '../src/p2-016-ticket-query.mjs';
import { createP2016DeliveryControl } from '../src/p2-016-delivery-control.mjs';
import { createCommunicationDeliveryWorker } from '../src/p2-004-communication-delivery-worker.mjs';
import { transactionP2016 } from '../src/p2-016-domain-contracts.mjs';
import { seedPersistedIntake } from './helpers/p2-015-postgres-harness.mjs';
import { withP2016IsolatedDatabase,applyThrough030 } from './helpers/p2-016-postgres-harness.mjs';
import { migrateP2016 } from '../scripts/p2-016-migrate.mjs';
test('Ticket delivery operator commands authorize before receipt, persist idempotence and never blindly retry UNKNOWN',async()=>{
  await withP2016IsolatedDatabase({databaseUrl:process.env.PILOT_DATABASE_URL,purpose:'p2016dc',run:async({pool,databaseUrl})=>{
    await applyThrough030({pool,databaseUrl});await migrateP2016({databaseUrl});
    const access=createPilotAccessService({pool}),principal=async(role)=>access.upsertPrincipal({wecomUserId:'synthetic-dc-'+role,displayName:'合成 '+role,roles:[role],resolverTeamIds:['PILOT_IT']});
    const admin=await principal('ADMIN'),dispatcher=await principal('DISPATCHER'),handler=await principal('HANDLER');
    const input=await seedPersistedIntake({pool,text:'合成故障',chatType:'single',requestType:'INCIDENT',status:'RECEIVED'});
    const ticket=(await createPilotTicketCore({pool}).createForIntake({intakeId:input.intakeId,occurredAt:input.receivedAt,traceId:'synthetic-dc'})).ticket;
    const n=await transactionP2016(pool,async tx=>{const event=await appendTicketEvent({transaction:tx,ticket,eventType:'ticket.created',actor:{type:'SYSTEM',id:null},traceId:'synthetic-dc'});return createP2016TicketNotificationProjector({enabled:true}).project({transaction:tx,ticket,event});});
    let mode='REJECTED_NOT_APPLIED',calls=0;
    const worker=createCommunicationDeliveryWorker({pool,enabled:true,sender:{send:async()=>{calls++;return {outcome:mode,provider_message_id:mode==='ACKNOWLEDGED'?'synthetic-ack':null,error_code:mode==='ACKNOWLEDGED'?null:'SYNTHETIC_NO_ACK',retryable:false};}}});
    assert.equal((await worker.deliver({deliveryId:n.delivery_id})).status,'DEAD_LETTER');
    const control=createP2016DeliveryControl({pool,query:createP2016TicketQuery({pool,enabled:true}),enabled:true});
    const command={ticketId:ticket.id,deliveryId:n.delivery_id,action:'retry',body:{client_command_id:randomUUID(),reason_code:'OPERATOR_VERIFIED'}};
    await assert.rejects(control.perform({...command,authContext:{principal_id:handler.id}}),{code:'P2_016_FORBIDDEN'});
    const retried=await Promise.all(Array.from({length:12},()=>control.perform({...command,authContext:{principal_id:admin.id}})));
    assert.equal(retried.filter(r=>!r.replayed).length,1);
    assert.ok(retried.every(r=>r.ok&&r.status==='PENDING'),JSON.stringify(retried[0]));
    await assert.rejects(control.perform({...command,authContext:{principal_id:admin.id},body:{...command.body,reason_code:'DIFFERENT'}}),{code:'P2_016_COMMAND_CONFLICT'});
    mode='UNKNOWN';assert.equal((await worker.deliver({deliveryId:n.delivery_id})).status,'RECONCILIATION_REQUIRED');const before=calls;
    const blocked=await control.perform({...command,authContext:{principal_id:admin.id},body:{...command.body,client_command_id:randomUUID()}});assert.equal(blocked.ok,false);
    assert.equal(await worker.deliver({deliveryId:n.delivery_id}),null);assert.equal(calls,before);
    const reconcile={...command,action:'reconcile',body:{client_command_id:randomUUID(),reason_code:'VERIFIED_NOT_SENT',resolution:'CONFIRMED_NOT_SENT_REQUEUE'}};
    await assert.rejects(control.perform({...reconcile,authContext:{principal_id:dispatcher.id}}),{code:'P2_016_FORBIDDEN'});
    assert.equal((await control.perform({...reconcile,authContext:{principal_id:admin.id}})).status,'PENDING');
    assert.equal((await control.perform({...reconcile,authContext:{principal_id:admin.id}})).replayed,true);
    mode='ACKNOWLEDGED';assert.equal((await worker.deliver({deliveryId:n.delivery_id})).status,'SENT');
    assert.equal(await worker.deliver({deliveryId:n.delivery_id}),null);assert.equal(calls,before+1);
    assert.equal((await pool.query('SELECT count(*)::integer AS n FROM communication.message')).rows[0].n,1);
  }});
});
