import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { test } from 'node:test';

import { applyChannelMessageInboxMigration } from '../src/p1-003-channel-message-inbox.mjs';
import { applyServiceIntakeMigration } from '../src/p1-004-service-intake.mjs';
import { applyPilotTicketCoreMigration } from '../src/p1-005-pilot-ticket-core.mjs';
import { applyPilotAccessMigration, createPilotAccessService } from '../src/p1-009-pilot-access-workbench.mjs';
import { applyConversationContractsMigration, buildConversationSessionScope, buildConversationThreadIdentity } from '../src/p2-001-conversation-contracts.mjs';
import { applyTimelineProjectionMigration } from '../src/p2-002-timeline-projector.mjs';
import { appendRealtimeEvent, applyRealtimeEventLogMigration } from '../src/p2-003-realtime-event-log.mjs';
import { applyCommunicationMigration, appendCommunication } from '../src/p2-004-communication-core.mjs';
import {
  CONVERSATION_CONTROL_ERROR_CODES, applyConversationControlMigration,
  createConversationControlService, createPilotConversationControlAuthorization,
  captureGenerationFence, assertGenerationFence, createAssignedCommunicationAuthorizer,
} from '../src/p2-005-conversation-control.mjs';
import { assertNoP2005Residual, withP2005IsolatedDatabase } from './helpers/p2-005-postgres-harness.mjs';

const execFileAsync=promisify(execFile); const databaseUrl=process.env.PILOT_DATABASE_URL;
if(typeof databaseUrl!=='string'||databaseUrl.length===0) throw new Error('P2_005_INTEGRATION_DATABASE_REQUIRED');
const TIMEOUT=240_000;

async function base(pool){await applyChannelMessageInboxMigration({pool});await applyServiceIntakeMigration({pool});await applyPilotTicketCoreMigration({pool});await applyPilotAccessMigration({pool});await applyConversationContractsMigration({pool});await applyTimelineProjectionMigration({pool});await applyRealtimeEventLogMigration({pool});await applyCommunicationMigration({pool});}
async function principal(pool,label,roles=['ADMIN'],teams=[]){return createPilotAccessService({pool}).upsertPrincipal({wecomUserId:`synthetic-${label}-${randomUUID()}`,displayName:`Synthetic ${label}`,roles,resolverTeamIds:teams});}
async function session(pool,label,{status='OPEN',controlMode='HUMAN',rowVersion=1,serviceIntakeId=null}={}){const identity=buildConversationThreadIdentity({provider:'WECOM_AIBOT',botId:`synthetic-${label}`,chatType:'group',chatId:`synthetic-group-${label}`,senderUserId:`synthetic-participant-${label}`});const t=await pool.query(`INSERT INTO conversation.thread(provider,channel_account_id,chat_type,external_thread_key,thread_key) VALUES($1,$2,$3,$4,$5) RETURNING id::text`,[identity.provider,identity.channel_account_id,identity.chat_type,identity.external_thread_key,identity.thread_key]);const scope=buildConversationSessionScope({threadKey:identity.thread_key,participantKey:identity.participant_key,serviceIntakeId,creationIdempotencyKey:`P2-005:${label}:${randomUUID()}`});const s=await pool.query(`INSERT INTO conversation.session(thread_id,participant_key,service_intake_id,session_scope_key,creation_idempotency_key,status,control_mode,row_version,last_activity_at,ended_at,close_reason) VALUES($1::uuid,$2,$3::uuid,$4,$5,$6,$7,$8,'2026-08-31T00:00:00Z',CASE WHEN $6='ENDED' THEN '2026-08-31T00:01:00Z'::timestamptz END,CASE WHEN $6='ENDED' THEN 'SYNTHETIC_END' END) RETURNING id::text,row_version::integer,generation_version::integer,control_mode`,[t.rows[0].id,scope.participant_key,serviceIntakeId,scope.session_scope_key,scope.creation_idempotency_key,status,controlMode,rowVersion]);return s.rows[0];}
function control(pool){const authorization=createPilotConversationControlAuthorization({pool});return {service:createConversationControlService({pool,enabled:true,authorize:authorization,realtimeAppender:appendRealtimeEvent,now:()=>new Date('2026-08-31T02:00:00Z')}),authorization};}
function command(type,s,actor,overrides={}){return {command_type:type,session_id:s.id,client_command_id:randomUUID(),idempotency_scope:'P2_005_TEST',expected_row_version:s.row_version,actor_principal_id:actor.id,target_principal_id:['TAKEOVER','TRANSFER'].includes(type)?actor.id:null,reason_code:type==='INVALIDATE_GENERATION'?'USER_MESSAGE_COMMITTED':type,...overrides};}
async function current(pool,id){return (await pool.query('SELECT id::text,row_version::integer,generation_version::integer,control_mode FROM conversation.session WHERE id=$1::uuid',[id])).rows[0];}
async function tables(pool){return (await pool.query(`SELECT schemaname||'.'||tablename name FROM pg_tables WHERE schemaname!~'^pg_' AND schemaname<>'information_schema' ORDER BY 1`)).rows.map(r=>r.name);}
async function cli(url,flag){const {stdout,stderr}=await execFileAsync(process.execPath,['scripts/p2-005-migrate.mjs',flag],{cwd:process.cwd(),env:{...process.env,PILOT_DATABASE_URL:url},timeout:30_000});assert.equal(stderr,'');assert.equal(stdout.includes(url),false);return JSON.parse(stdout);}

test('migration 021 is scoped, reentrant, check-rolls-back, and drift fails closed', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'migration',run:async({pool,databaseUrl:url})=>{await base(pool);const before=await tables(pool);const checked=await cli(url,'--check');assert.equal(checked.ok,true);assert.deepEqual(await tables(pool),before);await applyConversationControlMigration({pool});await applyConversationControlMigration({pool});assert.deepEqual((await tables(pool)).filter(x=>!before.includes(x)),['conversation.assignment','conversation.control_event','conversation.handoff','conversation.read_cursor']);const forbidden=await pool.query(`SELECT (SELECT count(*)::integer FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='conversation' AND p.proname LIKE 'p2_005%') routines,(SELECT count(*)::integer FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='conversation' AND NOT t.tgisinternal) triggers`);assert.deepEqual(forbidden.rows[0],{routines:0,triggers:0});t.diagnostic(JSON.stringify({first_apply:true,repeated_apply:true,check_rollback:true,new_tables:4}));}});
  for(const [purpose,sql] of [['missing','ALTER TABLE conversation.assignment DROP COLUMN released_at'],['weak','ALTER TABLE conversation.assignment DROP CONSTRAINT conversation_assignment_version_check; ALTER TABLE conversation.assignment ADD CONSTRAINT conversation_assignment_version_check CHECK(true)'],['unique','ALTER TABLE conversation.control_event DROP CONSTRAINT conversation_control_event_command_unique; ALTER TABLE conversation.control_event ADD CONSTRAINT conversation_control_event_command_unique UNIQUE(client_command_id,idempotency_scope)'],['method',"DROP INDEX conversation.conversation_handoff_one_active_per_session_idx; CREATE INDEX conversation_handoff_one_active_per_session_idx ON conversation.handoff USING hash(session_id) WHERE status IN ('REQUESTED','ACCEPTED')"],['predicate',"DROP INDEX conversation.conversation_handoff_one_active_per_session_idx; CREATE UNIQUE INDEX conversation_handoff_one_active_per_session_idx ON conversation.handoff(session_id) WHERE status='REQUESTED'"]]) await withP2005IsolatedDatabase({databaseUrl,purpose,run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});await pool.query(sql);await assert.rejects(applyConversationControlMigration({pool}),e=>e.code===CONVERSATION_CONTROL_ERROR_CODES.schemaDrift,purpose);}});
});

test('takeover is serialized/idempotent; handoff request-accept-release and request-cancel are audited atomically', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'lifecycle',run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});const a=await principal(pool,'admin-a'),b=await principal(pool,'admin-b');let s=await session(pool,'race');const {service}=control(pool);
    const c1=command('TAKEOVER',s,a,{target_principal_id:a.id}),c2=command('TAKEOVER',s,b,{target_principal_id:b.id});const race=await Promise.all([service.takeoverSession(c1),service.takeoverSession(c2)]);assert.equal(race.filter(x=>x.ok).length,1,JSON.stringify(race));assert.equal(race.filter(x=>x.error?.code===CONVERSATION_CONTROL_ERROR_CODES.sessionVersionConflict).length,1,JSON.stringify(race));
    s=await session(pool,'idem');const same=command('TAKEOVER',s,a,{target_principal_id:a.id});const twelve=await Promise.all(Array.from({length:12},()=>service.takeoverSession(same)));assert.equal(twelve.filter(x=>x.ok&&!x.replayed).length,1);assert.equal(twelve.filter(x=>x.ok&&x.replayed).length,11);assert.equal((await pool.query('SELECT count(*)::integer count FROM conversation.control_event WHERE session_id=$1::uuid',[s.id])).rows[0].count,1);
    let h=await session(pool,'handoff',{controlMode:'AUTO'});let request=await service.requestHandoff(command('REQUEST_HANDOFF',h,a,{requested_by_kind:'ADMIN',reason_code:'HANDOFF_REQUESTED'}));assert.equal(request.handoff.status,'REQUESTED');h=await current(pool,h.id);let accepted=await service.takeoverSession(command('TAKEOVER',h,a,{target_principal_id:a.id,handoff_id:request.handoff.id,reason_code:'HUMAN_TAKEOVER'}));assert.equal(accepted.handoff.status,'ACCEPTED');assert.equal(accepted.session.control_mode,'HUMAN');assert.equal(accepted.session.generation_version,h.generation_version+1);h=await current(pool,h.id);const released=await service.releaseAssignment(command('RELEASE',h,a,{target_principal_id:null,reason_code:'ASSIGNMENT_RELEASED'}));assert.equal(released.assignment.assignment_status,'UNASSIGNED');assert.equal(released.handoff.status,'RELEASED');assert.equal(released.session.control_mode,'HUMAN');
    let x=await session(pool,'cancel');const req=await service.requestHandoff(command('REQUEST_HANDOFF',x,a,{requested_by_kind:'ADMIN',reason_code:'HANDOFF_REQUESTED'}));x=await current(pool,x.id);const cancelled=await service.cancelHandoff(command('CANCEL_HANDOFF',x,a,{handoff_id:req.handoff.id,target_principal_id:null,reason_code:'HANDOFF_CANCELLED'}));assert.equal(cancelled.handoff.status,'CANCELLED');const events=await pool.query('SELECT event_ordinal::integer,event_type FROM conversation.control_event WHERE session_id=$1::uuid ORDER BY event_ordinal',[h.id]);assert.deepEqual(events.rows.map(r=>r.event_ordinal),[1,2,3]);t.diagnostic(JSON.stringify({concurrent_winners:1,idempotent_parallel:12,handoff:['REQUESTED','ACCEPTED','RELEASED'],cancel:'CANCELLED'}));}});
});

test('admin force transfer works; non-admin, inactive target, wrong-team handler, ended and stale commands fail closed', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'auth',run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});const admin=await principal(pool,'admin'),handler=await principal(pool,'handler',['HANDLER']),target=await principal(pool,'target',['HANDLER']);let s=await session(pool,'auth');const {service}=control(pool);await service.takeoverSession(command('TAKEOVER',s,admin,{target_principal_id:admin.id}));s=await current(pool,s.id);const transferred=await service.transferAssignment(command('TRANSFER',s,admin,{target_principal_id:target.id,force:true,reason_code:'ADMIN_TRANSFER'}));assert.equal(transferred.assignment.assignment_version,2);s=await current(pool,s.id);const forbidden=await service.transferAssignment(command('TRANSFER',s,handler,{target_principal_id:admin.id,force:true,reason_code:'FORCE_TRANSFER'}));assert.equal(forbidden.error.code,CONVERSATION_CONTROL_ERROR_CODES.forceTransferForbidden);await pool.query('UPDATE pilot_ticket.pilot_principal SET is_active=false WHERE id=$1::uuid',[handler.id]);const inactive=await service.takeoverSession(command('TAKEOVER',await session(pool,'inactive'),handler,{target_principal_id:handler.id}));assert.equal(inactive.error.code,CONVERSATION_CONTROL_ERROR_CODES.unauthorized);const wrong=await service.takeoverSession(command('TAKEOVER',await session(pool,'wrongteam'),target,{target_principal_id:target.id}));assert.equal(wrong.error.code,CONVERSATION_CONTROL_ERROR_CODES.unauthorized);const ended=await service.takeoverSession(command('TAKEOVER',await session(pool,'ended',{status:'ENDED'}),admin,{target_principal_id:admin.id}));assert.equal(ended.error.code,CONVERSATION_CONTROL_ERROR_CODES.sessionEnded);const stale=await service.takeoverSession(command('TAKEOVER',await session(pool,'stale',{rowVersion:3}),admin,{expected_row_version:2,target_principal_id:admin.id}));assert.equal(stale.error.code,CONVERSATION_CONTROL_ERROR_CODES.sessionVersionConflict);t.diagnostic(JSON.stringify({admin_force_transfer:true,handler_force:false,inactive:false,wrong_team:false}));}});
});

test('generation race blocks stale AI before Communication and realtime failure rolls back control facts', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'fence',run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});const admin=await principal(pool,'admin');let s=await session(pool,'fence',{controlMode:'COPILOT'});const client=await pool.connect();let fence;try{await client.query('BEGIN');fence=await captureGenerationFence({transaction:client,sessionId:s.id});await client.query('COMMIT');}finally{client.release();}const {service,authorization}=control(pool);await service.takeoverSession(command('TAKEOVER',s,admin,{target_principal_id:admin.id}));const before=await pool.query(`SELECT (SELECT count(*)::integer FROM communication.message) messages,(SELECT count(*)::integer FROM communication.outbox) outboxes,(SELECT count(*)::integer FROM communication.delivery) deliveries`);let appendCalls=0;const check=await pool.connect();try{await check.query('BEGIN');const stale=await assertGenerationFence({transaction:check,sessionId:s.id,generationVersionAtStart:fence.generation_version_at_start,allowedModes:['COPILOT','AUTO']});assert.equal(stale.error.code,CONVERSATION_CONTROL_ERROR_CODES.generationStale);if(stale.ok) {appendCalls++;await appendCommunication({transaction:check,command:{}});}await check.query('ROLLBACK');}finally{check.release();}assert.equal(appendCalls,0);const after=await pool.query(`SELECT (SELECT count(*)::integer FROM communication.message) messages,(SELECT count(*)::integer FROM communication.outbox) outboxes,(SELECT count(*)::integer FROM communication.delivery) deliveries`);assert.deepEqual(after.rows,before.rows);
    const authorizer=createAssignedCommunicationAuthorizer({controlService:service,featureFlags:{},authorization});const tx=await pool.connect();try{await tx.query('BEGIN');const denied=await authorizer({transaction:tx,command:{purpose:'AI_REPLY',sender_kind:'AI',session_id:s.id},actor:{generation_version_at_start:fence.generation_version_at_start},session:{control_mode:'HUMAN'}});assert.equal(denied,false);await tx.query('ROLLBACK');}finally{tx.release();}
    const rollbackSession=await session(pool,'rollback');const broken=createConversationControlService({pool,enabled:true,authorize:createPilotConversationControlAuthorization({pool}),realtimeAppender:async()=>{throw new Error('synthetic realtime failure');}});const failed=await broken.takeoverSession(command('TAKEOVER',rollbackSession,admin,{target_principal_id:admin.id}));assert.equal(failed.error.code,CONVERSATION_CONTROL_ERROR_CODES.storageFailed);assert.equal((await pool.query('SELECT count(*)::integer count FROM conversation.assignment WHERE session_id=$1::uuid',[rollbackSession.id])).rows[0].count,0);assert.equal((await current(pool,rollbackSession.id)).row_version,rollbackSession.row_version);t.diagnostic(JSON.stringify({generation_start:fence.generation_version_at_start,stale:true,append_communication_calls:0,message_delta:0,outbox_delta:0,delivery_delta:0,realtime_failure_rollback:true}));}});
});

test('32 principals keep independent monotonic cursors; visibility COUNT is correct and Session versions do not move', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'cursor',max:4,run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});const admin=await principal(pool,'admin');const principals=[admin];for(let i=1;i<32;i++)principals.push(await principal(pool,`cursor-${i}`,['ADMIN']));const s=await session(pool,'cursor');for(const [sequence,visibility] of [[1,'EXTERNAL'],[2,'INTERNAL'],[3,'RESTRICTED'],[4,'EXTERNAL']])await pool.query(`INSERT INTO conversation.item(session_id,sequence_no,item_type,sender_kind,visibility,text,safe_content,source_type,source_id,projection_variant,canonical_order_key,content_hash,privacy_class,retention_until,occurred_at) VALUES($1::uuid,$2,'SYSTEM_EVENT','SYSTEM',$3,NULL,'{}','HANDOFF_EVENT',$4,'CURSOR_FIXTURE',$5,$6,'INTERNAL','2027-08-31T00:00:00Z','2026-08-31T00:00:00Z')`,[s.id,sequence,visibility,`cursor-${sequence}`,`cursor-key-${sequence}`,'a'.repeat(64)]);const before=await current(pool,s.id);const {service}=control(pool);const updates=await Promise.all(principals.map((p,index)=>service.advanceReadCursor({command_type:'ADVANCE_READ_CURSOR',session_id:s.id,client_command_id:randomUUID(),idempotency_scope:`CURSOR_${index}`,expected_cursor_row_version:0,actor_principal_id:p.id,last_read_sequence:index%2?2:4,reason_code:'READ_CURSOR'})));assert.equal(updates.filter(x=>x.ok).length,32,JSON.stringify(updates));const after=await current(pool,s.id);assert.deepEqual({row:after.row_version,generation:after.generation_version},{row:before.row_version,generation:before.generation_version});const cursor=await service.getReadCursor({sessionId:s.id,principalId:admin.id});const noop=await service.advanceReadCursor({command_type:'ADVANCE_READ_CURSOR',session_id:s.id,client_command_id:randomUUID(),idempotency_scope:'CURSOR_NOOP',expected_cursor_row_version:cursor.cursor.row_version,actor_principal_id:admin.id,last_read_sequence:3,reason_code:'READ_CURSOR'});assert.equal(noop.no_op,true);const ahead=await service.advanceReadCursor({command_type:'ADVANCE_READ_CURSOR',session_id:s.id,client_command_id:randomUUID(),idempotency_scope:'CURSOR_AHEAD',expected_cursor_row_version:cursor.cursor.row_version,actor_principal_id:admin.id,last_read_sequence:99,reason_code:'READ_CURSOR'});assert.equal(ahead.error.code,CONVERSATION_CONTROL_ERROR_CODES.cursorAhead);const unreadWorkbench=await service.countUnreadItems({sessionId:s.id,principalId:principals[1].id,audience:'WORKBENCH'});const unreadRestricted=await service.countUnreadItems({sessionId:s.id,principalId:principals[1].id,audience:'RESTRICTED_ADMIN'});assert.deepEqual([unreadWorkbench.unread_count,unreadRestricted.unread_count],[1,2]);t.diagnostic(JSON.stringify({principals:32,monotonic:true,session_version_unchanged:true,workbench_unread:1,restricted_unread:2}));}});
});

test('2C4G bounded capacity covers 500 assignment/handoff facts and 2,000 cursor updates without residual resources', {timeout:TIMEOUT}, async t=>{
  await withP2005IsolatedDatabase({databaseUrl,purpose:'capacity',max:4,run:async({pool})=>{await base(pool);await applyConversationControlMigration({pool});const admin=await principal(pool,'capacity');const heap=[];for(let block=0;block<5;block++){for(let i=0;i<100;i++){const s=await session(pool,`capacity-${block}-${i}`);await pool.query(`INSERT INTO conversation.assignment(session_id,assignment_status,assigned_principal_id,assigned_by_principal_id,assigned_at) VALUES($1::uuid,'ASSIGNED',$2::uuid,$2::uuid,'2026-08-31T00:00:00Z')`,[s.id,admin.id]);await pool.query(`INSERT INTO conversation.handoff(session_id,status,requested_by_kind,requested_by_principal_id,reason_code,from_mode,to_mode,assigned_principal_id,request_command_id,request_hash,requested_at,accepted_at,updated_at) VALUES($1::uuid,'ACCEPTED','ADMIN',$2::uuid,'CAPACITY','HUMAN','HUMAN',$2::uuid,$3::uuid,$4,'2026-08-31T00:00:00Z','2026-08-31T00:00:00Z','2026-08-31T00:00:00Z')`,[s.id,admin.id,randomUUID(),'b'.repeat(64)]);if(block===0&&i===0)await pool.query(`INSERT INTO conversation.read_cursor(principal_id,session_id,last_read_sequence) VALUES($1::uuid,$2::uuid,0)`,[admin.id,s.id]);if(block===0&&i===0)await pool.query(`DO $do$ BEGIN FOR n IN 1..2000 LOOP UPDATE conversation.read_cursor SET last_read_sequence=n,row_version=row_version+1,updated_at=clock_timestamp() WHERE principal_id='${admin.id}'::uuid AND session_id='${s.id}'::uuid; END LOOP; END $do$;`);}heap.push(process.memoryUsage().heapUsed);}const counts=await pool.query(`SELECT (SELECT count(*)::integer FROM conversation.assignment) assignments,(SELECT count(*)::integer FROM conversation.handoff) handoffs,(SELECT max(row_version)::integer FROM conversation.read_cursor) cursor_version`);assert.deepEqual(counts.rows[0],{assignments:500,handoffs:500,cursor_version:2001});assert.equal(heap.every(Number.isFinite),true);assert.ok(Math.max(...heap)-Math.min(...heap)<128*1024*1024);t.diagnostic(JSON.stringify({assignments:500,handoffs:500,cursor_updates:2000,max_list_limit:200,heap_samples:heap.length,heap_monotonic_unbounded:false,pool_max:4,soak_24h:false}));}});await assertNoP2005Residual({databaseUrl});
});
